# 03 Embeddings

This notebook builds quarter-specific GraphSAGE and Node2Vec embeddings and exports pooled datasets for later regression experiments in a separate notebook.

In [2]:
import sys
import os
from pathlib import Path

%matplotlib inline

sys.path.insert(0, os.path.abspath('../..'))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from src.models.embeddings import GNNConfig, Node2VecConfig
from src.models.embedding_pipeline import build_pooled_dataset

PROJECT_ROOT = Path().resolve().parents[1]
DATA_PATH = PROJECT_ROOT / 'datasets'
OUTPUT_ROOT = PROJECT_ROOT / 'src' / 'data'

pd.set_option("display.max_columns", 200)

## Configuration

In [3]:
cfg_graphsage = GNNConfig(
    hidden_dims=(256, 64),
    dropout=0.3,
    lr=0.01,
    epochs=100,
    aggregation="mean",
    device="cpu",
)

cfg_node2vec = Node2VecConfig(
    embedding_dim=64,
    walk_length=20,
    context_size=10,
    walks_per_node=10,
    num_negative_samples=1,
    batch_size=128,
    lr=0.01,
    epochs=100,
    device="cpu",
)

TARGET_COL = "systemic_risk_label"
INCLUDE_RAW_FEATURES = False

OUTPUT_DATASET_GRAPHSAGE = PROJECT_ROOT / "src" / "data" / "embeddings" / "graphsage_srisk_dataset.parquet"
OUTPUT_DATASET_NODE2VEC = PROJECT_ROOT / "src" / "data" / "embeddings" / "node2vec_srisk_dataset.parquet"

OUTPUT_DATASET_GRAPHSAGE, OUTPUT_DATASET_NODE2VEC

(WindowsPath('C:/Users/ruben/Desktop/Universidade/Nova IMS/Tese/Thesis/src/data/embeddings/graphsage_srisk_dataset.parquet'),
 WindowsPath('C:/Users/ruben/Desktop/Universidade/Nova IMS/Tese/Thesis/src/data/embeddings/node2vec_srisk_dataset.parquet'))

# Build Embedding Dataset

## GraphSAGE

For each quarter, GraphSAGE is trained on that quarter's graph only. The resulting embeddings are merged with the regression target `systemic_risk_label` and optionally with the raw node features.

In [4]:
pooled_df_graphsage = build_pooled_dataset(
    config=cfg_graphsage,
    years=range(2016, 2024),
    quarters=(1, 2, 3, 4),
    target_col=TARGET_COL,
    include_raw_features=INCLUDE_RAW_FEATURES,
    output_path=OUTPUT_DATASET_GRAPHSAGE,
)

pooled_df_graphsage.shape

Loaded 2016 Q1: 4548 banks, 11631 edges
Loaded 2016 Q2: 4548 banks, 11632 edges
Loaded 2016 Q3: 4548 banks, 11937 edges
Loaded 2016 Q4: 4548 banks, 11938 edges
Loaded 2017 Q1: 4548 banks, 11939 edges
Loaded 2017 Q2: 4548 banks, 11940 edges
Loaded 2017 Q3: 4548 banks, 11941 edges
Loaded 2017 Q4: 4548 banks, 11981 edges
Loaded 2018 Q1: 4548 banks, 12416 edges
Loaded 2018 Q2: 4548 banks, 12417 edges
Loaded 2018 Q3: 4548 banks, 12418 edges
Loaded 2018 Q4: 4548 banks, 12419 edges
Loaded 2019 Q1: 4548 banks, 12420 edges
Loaded 2019 Q2: 4548 banks, 12421 edges
Loaded 2019 Q3: 4548 banks, 12422 edges
Loaded 2019 Q4: 4548 banks, 12423 edges
Loaded 2020 Q1: 4548 banks, 12424 edges
Loaded 2020 Q2: 4548 banks, 12451 edges
Loaded 2020 Q3: 4548 banks, 12452 edges
Loaded 2020 Q4: 4548 banks, 12453 edges
Loaded 2021 Q1: 4548 banks, 12454 edges
Loaded 2021 Q2: 4548 banks, 12455 edges
Loaded 2021 Q3: 4548 banks, 12456 edges
Loaded 2021 Q4: 4548 banks, 12457 edges
Loaded 2022 Q1: 4548 banks, 12458 edges
Loaded 2022 Q2: 4548 banks, 12459 edges
Loaded 2022 Q3: 4548 banks, 12460 edges
Loaded 2022 Q4: 4548 banks, 12461 edges
Loaded 2023 Q1: 4548 banks, 12462 edges
Loaded 2023 Q2: 4548 banks, 12463 edges
Loaded 2023 Q3: 4548 banks, 12464 edges
Loaded 2023 Q4: 4548 banks, 12465 edges

(145536, 69)

In [5]:
pooled_df_graphsage.head()

,bank_id,year,quarter,period,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,emb_9,emb_10,emb_11,emb_12,emb_13,emb_14,emb_15,emb_16,emb_17,emb_18,emb_19,emb_20,emb_21,emb_22,emb_23,emb_24,emb_25,emb_26,emb_27,emb_28,emb_29,emb_30,emb_31,emb_32,emb_33,emb_34,emb_35,emb_36,emb_37,emb_38,emb_39,emb_40,emb_41,emb_42,emb_43,emb_44,emb_45,emb_46,emb_47,emb_48,emb_49,emb_50,emb_51,emb_52,emb_53,emb_54,emb_55,emb_56,emb_57,emb_58,emb_59,emb_60,emb_61,emb_62,emb_63,systemic_risk_label
0,0,2016,1,2016Q1,0.128626,-0.263438,-0.611569,-0.646356,-0.727332,-0.196355,-0.588948,0.248189,-0.013566,0.281105,0.267774,-0.095213,-0.295462,0.345485,-0.360512,0.703092,1.162910,-0.251759,0.836428,-0.068685,-0.416449,0.257503,0.194684,0.397772,-0.639560,0.351693,0.004369,0.585069,-0.628221,0.382420,-0.156891,-0.488145,0.496105,-0.103851,-0.369773,0.531042,0.170773,0.936489,-0.488644,0.388305,0.241537,0.108994,0.041691,-0.915571,-0.746299,0.774405,0.498254,-0.144478,-0.609622,-0.787699,-0.212953,-0.172338,-0.665161,-0.115398,0.546671,-0.664472,0.612682,-0.156020,-0.222993,-0.265075,0.239481,0.255344,-0.083118,0.056184,215
1,1,2016,1,2016Q1,0.097630,-0.276081,-0.577364,-0.227166,-0.736315,-0.038153,-0.674528,0.073023,0.023033,0.169663,0.288402,0.116630,-0.212485,0.419117,-0.302565,0.498100,1.013683,-0.301567,0.759446,0.099539,-0.128170,0.343339,0.156831,0.498780,-0.290543,0.251744,0.023491,0.456059,-0.637681,0.139627,-0.302286,-0.596716,0.476769,-0.153372,-0.166289,0.455603,0.183422,0.704069,-0.311679,0.476220,0.028510,0.106012,-0.048878,-0.793697,-0.611455,0.584388,0.237323,-0.252354,-0.484601,-0.523563,-0.172247,-0.175528,-0.497604,-0.210057,0.315549,-0.685360,0.547094,-0.281614,-0.123897,-0.085781,0.288586,0.016396,-0.176686,-0.129925,20
2,2,2016,1,2016Q1,0.207097,-0.162293,-0.565283,-0.343029,-0.540327,-0.169697,-0.356936,0.194332,0.207416,0.310686,0.373408,-0.211694,-0.220237,0.231959,-0.224062,0.381021,0.611087,-0.279941,0.525132,-0.246272,-0.238055,0.259067,-0.076772,0.345972,-0.297325,0.299708,-0.230244,0.268280,-0.487231,0.247446,-0.353559,-0.477814,0.341867,-0.280829,-0.188621,0.302423,0.326226,0.517495,-0.284440,0.070462,0.181010,0.025331,0.112822,-0.571112,-0.418157,0.427709,0.219165,-0.141545,-0.293191,-0.439886,-0.143885,-0.206517,-0.292380,-0.193758,0.292484,-0.406223,0.412920,-0.252047,0.130819,-0.161119,0.349404,0.149725,-0.190242,-0.153663,95
3,3,2016,1,2016Q1,0.038281,-0.398822,-0.790811,-0.082866,-0.899918,0.100794,-0.753546,0.065676,0.200806,0.130642,0.416927,0.034877,-0.209369,0.606702,-0.414482,0.364225,1.059064,-0.530431,0.851314,0.005230,-0.109820,0.490280,0.113706,0.755156,-0.263691,0.299287,-0.146163,0.504374,-0.937184,0.114776,-0.507877,-0.865103,0.539232,-0.337463,-0.132132,0.640681,0.400009,0.652372,-0.088560,0.599529,-0.199800,0.052917,-0.100140,-0.915279,-0.706930,0.629303,0.083797,-0.246015,-0.388880,-0.506659,-0.219305,-0.214547,-0.454227,-0.262674,0.311431,-0.746810,0.706486,-0.644910,-0.028678,0.051813,0.553761,-0.109697,-0.327144,-0.306742,37
4,4,2016,1,2016Q1,0.067765,-0.034311,-0.467285,-0.293372,-0.530799,-0.092634,-0.274928,0.094320,0.103892,0.193560,0.241975,-0.198015,-0.124464,0.218095,-0.168461,0.288938,0.670379,-0.288631,0.426908,-0.242910,-0.263269,0.130910,-0.029060,0.350547,-0.303726,0.198744,-0.176843,0.252927,-0.460431,0.271985,-0.250245,-0.420825,0.220039,-0.280324,-0.124181,0.341851,0.240137,0.519509,-0.098136,0.258261,0.053315,0.010434,-0.006740,-0.616676,-0.482503,0.359163,0.130488,-0.050621,-0.217586,-0.360449,-0.157553,-0.149492,-0.200154,-0.057213,0.159786,-0.262754,0.388852,-0.247299,0.107210,0.009249,0.371873,0.131984,-0.113866,0.023649,28

In [6]:
embedding_cols = [c for c in pooled_df_graphsage.columns if c.startswith("emb_")]
meta_cols = ["bank_id", "year", "quarter", "period", TARGET_COL]
meta_cols + embedding_cols[:5], len(embedding_cols)

(['bank_id',
  'year',
  'quarter',
  'period',
  'systemic_risk_label',
  'emb_0',
  'emb_1',
  'emb_2',
  'emb_3',
  'emb_4'],
 64)

In [7]:
pooled_df_graphsage.groupby(["year", "quarter"])[TARGET_COL].agg(["count", "mean", "max"]).head(12)

              count      mean  max
year quarter
2016 1         4548  1.239006  215
     2         4548  1.140062  112
     3         4548  1.101583   65
     4         4548  1.080695   28
2017 1         4548  1.083333   33
     2         4548  1.073879   41
     3         4548  1.073439   34
     4         4548  1.077177   31
2018 1         4548  1.108179   40
     2         4548  1.093668   37
     3         4548  1.080255   37
     4         4548  1.082674   29

## Node2Vec

Node2Vec is trained on quarter-specific graph structure using random walks. The resulting embeddings are merged with the same downstream target for comparison against GraphSAGE.

In [8]:
pooled_df_node2vec = build_pooled_dataset(
    config=cfg_node2vec,
    years=range(2016, 2024),
    quarters=(1, 2, 3, 4),
    target_col=TARGET_COL,
    include_raw_features=INCLUDE_RAW_FEATURES,
    output_path=OUTPUT_DATASET_NODE2VEC,
)

pooled_df_node2vec.shape

Loaded 2016 Q1: 4548 banks, 11631 edges
Loaded 2016 Q2: 4548 banks, 11632 edges
Loaded 2016 Q3: 4548 banks, 11937 edges
Loaded 2016 Q4: 4548 banks, 11938 edges
Loaded 2017 Q1: 4548 banks, 11939 edges
Loaded 2017 Q2: 4548 banks, 11940 edges
Loaded 2017 Q3: 4548 banks, 11941 edges
Loaded 2017 Q4: 4548 banks, 11981 edges
Loaded 2018 Q1: 4548 banks, 12416 edges
Loaded 2018 Q2: 4548 banks, 12417 edges
Loaded 2018 Q3: 4548 banks, 12418 edges
Loaded 2018 Q4: 4548 banks, 12419 edges
Loaded 2019 Q1: 4548 banks, 12420 edges
Loaded 2019 Q2: 4548 banks, 12421 edges
Loaded 2019 Q3: 4548 banks, 12422 edges
Loaded 2019 Q4: 4548 banks, 12423 edges
Loaded 2020 Q1: 4548 banks, 12424 edges
Loaded 2020 Q2: 4548 banks, 12451 edges
Loaded 2020 Q3: 4548 banks, 12452 edges
Loaded 2020 Q4: 4548 banks, 12453 edges
Loaded 2021 Q1: 4548 banks, 12454 edges
Loaded 2021 Q2: 4548 banks, 12455 edges
Loaded 2021 Q3: 4548 banks, 12456 edges
Loaded 2021 Q4: 4548 banks, 12457 edges
Loaded 2022 Q1: 4548 banks, 12458 edges
Loaded 2022 Q2: 4548 banks, 12459 edges
Loaded 2022 Q3: 4548 banks, 12460 edges
Loaded 2022 Q4: 4548 banks, 12461 edges
Loaded 2023 Q1: 4548 banks, 12462 edges
Loaded 2023 Q2: 4548 banks, 12463 edges
Loaded 2023 Q3: 4548 banks, 12464 edges
Loaded 2023 Q4: 4548 banks, 12465 edges

(145536, 69)

In [9]:
pooled_df_node2vec.head()

,bank_id,year,quarter,period,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,emb_9,emb_10,emb_11,emb_12,emb_13,emb_14,emb_15,emb_16,emb_17,emb_18,emb_19,emb_20,emb_21,emb_22,emb_23,emb_24,emb_25,emb_26,emb_27,emb_28,emb_29,emb_30,emb_31,emb_32,emb_33,emb_34,emb_35,emb_36,emb_37,emb_38,emb_39,emb_40,emb_41,emb_42,emb_43,emb_44,emb_45,emb_46,emb_47,emb_48,emb_49,emb_50,emb_51,emb_52,emb_53,emb_54,emb_55,emb_56,emb_57,emb_58,emb_59,emb_60,emb_61,emb_62,emb_63,systemic_risk_label
0,0,2016,1,2016Q1,-0.965620,0.384940,0.026495,3.169153,0.056678,-1.952258,-5.138675,0.381632,0.499294,1.473794,-0.539064,0.569590,1.878532,0.290422,4.912836,0.164801,-0.582104,-1.565917,-1.167479,-1.816634,0.086618,0.695355,-0.615855,-0.817767,-0.666420,0.502889,-2.676404,0.060189,-0.280046,-1.119448,0.896822,-0.395644,-2.102556,0.952198,-0.561613,2.624336,0.093714,-1.589805,-0.598768,-0.335640,0.484458,-0.446604,-4.352917,-0.107309,0.269313,0.078845,-0.939516,-6.924390,0.540252,-4.804036,-0.750746,1.546213,1.893679,-0.996871,5.143190,0.892991,0.634014,-0.932538,0.767247,-0.183518,1.017841,0.370474,1.786887,-0.250866,215
1,1,2016,1,2016Q1,-0.462659,0.025040,0.015683,2.233687,0.423754,-0.124605,-4.042871,0.304147,0.168651,1.852327,-0.465169,-0.319616,1.940756,-0.188117,3.394461,1.935575,-0.612043,-1.715289,-0.162391,-1.163381,-0.080048,-0.239861,-0.449900,-0.165053,-1.775973,-0.114937,-1.222703,0.228638,0.441184,-0.467178,-1.807514,-0.293660,-0.134179,-0.041470,-0.594291,0.678849,-0.198077,-0.243403,-0.288069,-0.304673,-0.213955,-0.096409,-4.040857,0.969651,0.005912,-0.053552,-0.234123,-1.036650,0.152427,-1.830178,0.861349,0.531872,0.988195,0.523334,3.669898,0.497331,1.472822,-0.950533,0.415725,-0.441446,-0.608432,-0.078218,0.564827,-1.456564,20
2,2,2016,1,2016Q1,-0.669921,0.062959,0.172145,1.929988,0.207052,-1.137748,-7.719783,-0.343808,-0.103499,2.338335,-0.054885,0.235203,0.728630,-0.366643,5.596461,0.028969,-1.400662,-1.822744,-0.331245,-0.967061,-0.107241,-1.500051,-0.450279,-0.405327,-0.080393,0.562382,-2.192271,0.304976,-1.000684,0.507580,0.103331,1.357445,-1.629549,0.665305,-1.777393,3.322035,0.212553,-0.764221,-1.439864,-0.632452,-0.289139,0.203261,-4.418323,0.636297,0.359694,-0.321734,-1.250356,-1.381091,0.279388,-0.787284,-0.343506,1.042243,-0.002047,0.213982,2.755963,0.558295,2.550426,-0.136725,1.043206,-0.152459,0.646045,0.243622,-0.738755,-0.386590,95
3,3,2016,1,2016Q1,-0.374560,-2.275612,0.395121,2.017096,0.327297,-1.514868,-6.482851,-0.382116,0.124864,1.064526,-0.753561,0.704489,1.108928,-0.115662,2.042980,-0.997755,-1.143986,-0.291461,-0.023931,-0.645621,-0.544385,-0.511538,-0.136904,0.235172,1.190494,-0.589405,-1.558244,0.553152,-0.581732,-0.629485,-0.065794,0.253156,-1.026365,-0.688206,-0.184102,1.387377,0.163057,-1.001250,0.066031,-0.343958,0.727643,0.213313,-7.026116,0.322596,0.048702,0.257006,-0.609227,-3.921592,0.542150,-3.394916,-0.314236,1.270258,0.699983,0.219560,2.605319,0.770701,2.201264,-0.717173,0.069520,0.185725,0.238970,0.193967,0.738090,-0.959402,37
4,4,2016,1,2016Q1,-1.681131,0.172814,0.078200,-0.384175,0.228888,-0.547217,-6.933330,-0.306692,1.132346,1.611064,0.601287,-0.967546,-0.494371,-0.743579,1.952052,0.428200,-1.343662,-0.646576,0.174656,-0.085621,-0.274612,-0.006267,-0.589334,-0.145743,1.365340,0.218390,-1.688127,-0.045271,-0.011129,-0.902652,0.565332,-0.227770,-1.122567,-0.498513,-1.098762,1.366682,0.217714,-0.826507,-1.069576,-0.464206,-0.253231,-0.586250,-4.409215,0.172592,-1.000513,-0.226901,0.067816,-0.803027,0.390783,-2.451425,0.183957,0.593969,-0.456007,-0.005619,1.878545,0.383603,2.632744,-0.334804,0.012566,-0.175060,-1.150573,0.062278,0.203379,0.623214,28

In [10]:
embedding_cols = [c for c in pooled_df_node2vec.columns if c.startswith("emb_")]
meta_cols = ["bank_id", "year", "quarter", "period", TARGET_COL]
meta_cols + embedding_cols[:5], len(embedding_cols)

(['bank_id',
  'year',
  'quarter',
  'period',
  'systemic_risk_label',
  'emb_0',
  'emb_1',
  'emb_2',
  'emb_3',
  'emb_4'],
 64)

In [11]:
pooled_df_node2vec.groupby(["year", "quarter"])[TARGET_COL].agg(["count", "mean", "max"]).head(12)

              count      mean  max
year quarter
2016 1         4548  1.239006  215
     2         4548  1.140062  112
     3         4548  1.101583   65
     4         4548  1.080695   28
2017 1         4548  1.083333   33
     2         4548  1.073879   41
     3         4548  1.073439   34
     4         4548  1.077177   31
2018 1         4548  1.108179   40
     2         4548  1.093668   37
     3         4548  1.080255   37
     4         4548  1.082674   29

# Exported Datasets

The saved datasets contain:
- metadata: `bank_id`, `year`, `quarter`, `period`
- target: `systemic_risk_label`
- embeddings: `emb_0`, `emb_1`, ...
- optional raw features from the node table

Files written by this notebook:
- `outputs/embeddings/graphsage_srisk_dataset.parquet`
- `outputs/embeddings/node2vec_srisk_dataset.parquet`

## Next Step

Use the exported parquet files in a separate notebook for classical machine-learning regression or model comparison.