# 06 - Embedding Model Result Comparison

This notebook compares the downstream ML results for every embedding dataset produced in the previous notebooks. Some embedding datasets use `log_systemic_risk_label`, while the no-log datasets use `systemic_risk_label`. To keep the comparison fair, every trained model is scored in both spaces:

- `metric_space == "log"`: errors are measured after converting targets/predictions to log scale.
- `metric_space == "out"`: errors are measured on the original systemic-risk scale.

`native_space` records the target space used during model training.

In [ ]:
from pathlib import Path
import os
import sys

sys.path.insert(0, os.path.abspath('../..'))

import numpy as np
import pandas as pd

from IPython.display import display
from sklearn.ensemble import HistGradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor

from src.models.ml_train_and_store import (
    ModelTrainer,
    load_gnn_dataset,
    make_pipeline,
)

pd.set_option('display.max_columns', 200)
pd.set_option('display.float_format', lambda x: f'{x:,.6f}')

PROJECT_ROOT = Path().resolve().parents[1]
print(f'Project root: {PROJECT_ROOT}')

## Dataset Registry

The `native_space` column says whether the dataset's training target is already log-transformed or in the original output scale.

In [ ]:
DATASETS = [
    {
        'dataset': 'GraphSAGE-v1-log',
        'embedding_model': 'GraphSAGE',
        'variant': 'v1-log',
        'filename': 'graphsage_srisk_dataset.parquet',
        'target_col': 'log_systemic_risk_label',
        'native_space': 'log',
    },
    {
        'dataset': 'Node2Vec-v1-log',
        'embedding_model': 'Node2Vec',
        'variant': 'v1-log',
        'filename': 'node2vec_srisk_dataset.parquet',
        'target_col': 'log_systemic_risk_label',
        'native_space': 'log',
    },
    {
        'dataset': 'GraphSAGE-v2-log',
        'embedding_model': 'GraphSAGE',
        'variant': 'v2-log',
        'filename': 'graphsage_fixed_srisk_dataset.parquet',
        'target_col': 'log_systemic_risk_label',
        'native_space': 'log',
    },
    {
        'dataset': 'GraphSAGE-v3-log',
        'embedding_model': 'GraphSAGE',
        'variant': 'v3-log',
        'filename': 'graphsage_fixed_128_srisk_dataset.parquet',
        'target_col': 'log_systemic_risk_label',
        'native_space': 'log',
    },
    {
        'dataset': 'Node2Vec-v2-log',
        'embedding_model': 'Node2Vec',
        'variant': 'v2-log',
        'filename': 'node2vec_fixed_srisk_dataset.parquet',
        'target_col': 'log_systemic_risk_label',
        'native_space': 'log',
    },
    {
        'dataset': 'Node2Vec-v3-log',
        'embedding_model': 'Node2Vec',
        'variant': 'v3-log',
        'filename': 'node2vec_fixed_v3_srisk_dataset.parquet',
        'target_col': 'log_systemic_risk_label',
        'native_space': 'log',
    },
    {
        'dataset': 'GraphSAGE-v2-nolog',
        'embedding_model': 'GraphSAGE',
        'variant': 'v2-nolog',
        'filename': 'graphsage_fixed_32_srisk_nolog_dataset.parquet',
        'target_col': 'systemic_risk_label',
        'native_space': 'out',
    },
    {
        'dataset': 'GraphSAGE-v3-nolog',
        'embedding_model': 'GraphSAGE',
        'variant': 'v3-nolog',
        'filename': 'graphsage_fixed_64_srisk_nolog_dataset.parquet',
        'target_col': 'systemic_risk_label',
        'native_space': 'out',
    },
    {
        'dataset': 'GraphSAGE-v4-nolog',
        'embedding_model': 'GraphSAGE',
        'variant': 'v4-nolog',
        'filename': 'graphsage_fixed_128_srisk_nolog_dataset.parquet',
        'target_col': 'systemic_risk_label',
        'native_space': 'out',
    },
    {
        'dataset': 'Node2Vec-v2-nolog',
        'embedding_model': 'Node2Vec',
        'variant': 'v2-nolog',
        'filename': 'node2vec_fixed_32_srisk_nolog_dataset.parquet',
        'target_col': 'systemic_risk_label',
        'native_space': 'out',
    },
    {
        'dataset': 'Node2Vec-v3-nolog',
        'embedding_model': 'Node2Vec',
        'variant': 'v3-nolog',
        'filename': 'node2vec_fixed_64_srisk_nolog_dataset.parquet',
        'target_col': 'systemic_risk_label',
        'native_space': 'out',
    },
    {
        'dataset': 'Node2Vec-v4-nolog',
        'embedding_model': 'Node2Vec',
        'variant': 'v4-nolog',
        'filename': 'node2vec_fixed_128_srisk_nolog_dataset.parquet',
        'target_col': 'systemic_risk_label',
        'native_space': 'out',
    },
]

pd.DataFrame(DATASETS)

## Load Embedding Datasets

In [3]:
loaded = {}
dataset_summary = []

for spec in DATASETS:
    df, feature_cols = load_gnn_dataset(
        PROJECT_ROOT,
        target_col=spec['target_col'],
        filename=spec['filename'],
    )
    loaded[spec['dataset']] = {'spec': spec, 'df': df, 'feature_cols': feature_cols}
    dataset_summary.append({
        **spec,
        'rows': len(df),
        'embedding_cols': len(feature_cols),
        'period_min': df['period'].min(),
        'period_max': df['period'].max(),
    })

dataset_summary = pd.DataFrame(dataset_summary)
dataset_summary.sort_values(['native_space', 'embedding_model', 'variant', 'dataset']).reset_index(drop=True)

,dataset,embedding_model,variant,filename,target_col,native_space,rows,embedding_cols,period_min,period_max
0,graphsage_fixed_32_log,GraphSAGE,fixed_32,graphsage_fixed_srisk_dataset.parquet,log_systemic_risk_label,log,145536,32,2016Q1,2023Q4
1,graphsage_original,GraphSAGE,original,graphsage_srisk_dataset.parquet,log_systemic_risk_label,log,145536,64,2016Q1,2023Q4
2,node2vec_fixed_128_log,Node2Vec,fixed_128,node2vec_fixed_v3_srisk_dataset.parquet,log_systemic_risk_label,log,145536,128,2016Q1,2023Q4
3,node2vec_fixed_32_log,Node2Vec,fixed_32,node2vec_fixed_srisk_dataset.parquet,log_systemic_risk_label,log,145536,32,2016Q1,2023Q4
4,node2vec_original,Node2Vec,original,node2vec_srisk_dataset.parquet,log_systemic_risk_label,log,145536,64,2016Q1,2023Q4
5,graphsage_fixed_32_out,GraphSAGE,fixed_32,graphsage_fixed_32_srisk_nolog_dataset.parquet,systemic_risk_label,out,145536,32,2016Q1,2023Q4
6,graphsage_fixed_64_out,GraphSAGE,fixed_64,graphsage_fixed_64_srisk_nolog_dataset.parquet,systemic_risk_label,out,145536,64,2016Q1,2023Q4
7,node2vec_fixed_32_out,Node2Vec,fixed_32,node2vec_fixed_32_srisk_nolog_dataset.parquet,systemic_risk_label,out,145536,32,2016Q1,2023Q4
8,node2vec_fixed_64_out,Node2Vec,fixed_64,node2vec_fixed_64_srisk_nolog_dataset.parquet,systemic_risk_label,out,145536,64,2016Q1,2023Q4

## Candidate Models

In [ ]:
candidate_models = {
    'Linear Regression': make_pipeline(LinearRegression()),
    'Ridge':             make_pipeline(Ridge(alpha=1.0)),
    'MLP':               make_pipeline(MLPRegressor(hidden_layer_sizes=(100,), max_iter=500, random_state=42)),
    'Random Forest':     make_pipeline(RandomForestRegressor(n_estimators=100, random_state=42)),
    'Gradient Boosting': make_pipeline(HistGradientBoostingRegressor(max_iter=200, random_state=42)),
    'XGBoost':           make_pipeline(XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)),
}

list(candidate_models)

## Scoring Helpers

For `out -> log` conversion, negative original-scale predictions are clipped at zero only for the log-space metric conversion. Original-scale metrics still use the raw model prediction.

In [5]:
def regression_scores(y_true, y_pred):
    return {
        'mae': mean_absolute_error(y_true, y_pred),
        'rmse': mean_squared_error(y_true, y_pred) ** 0.5,
        'r2': r2_score(y_true, y_pred),
    }


def values_in_metric_space(y_true_native, y_pred_native, native_space, metric_space):
    y_true_native = np.asarray(y_true_native, dtype=float)
    y_pred_native = np.asarray(y_pred_native, dtype=float)

    if native_space == metric_space:
        return y_true_native, y_pred_native

    if native_space == 'log' and metric_space == 'out':
        return np.expm1(y_true_native), np.expm1(y_pred_native)

    if native_space == 'out' and metric_space == 'log':
        return np.log1p(np.clip(y_true_native, 0, None)), np.log1p(np.clip(y_pred_native, 0, None))

    raise ValueError(f'Unsupported conversion: {native_space} -> {metric_space}')


def score_model_split(model, split_df, feature_cols, target_col, native_space, metric_space):
    y_true_native = split_df[target_col]
    y_pred_native = model.predict(split_df[feature_cols])
    y_true, y_pred = values_in_metric_space(y_true_native, y_pred_native, native_space, metric_space)
    return regression_scores(y_true, y_pred)

## Train and Compare All Embedding Models

In [ ]:
records = []
trainers = {}

for dataset_name, item in loaded.items():
    spec = item['spec']
    df = item['df']
    feature_cols = item['feature_cols']

    trainer = ModelTrainer(df=df, feature_cols=feature_cols, target_col=spec['target_col'])
    trainer.train_all(candidate_models)
    trainers[dataset_name] = trainer

    for model_name, model in trainer.models.items():
        for metric_space in ['log', 'out']:
            row = {
                'dataset': dataset_name,
                'embedding_model': spec['embedding_model'],
                'variant': spec['variant'],
                'embedding_cols': len(feature_cols),
                'native_space': spec['native_space'],
                'metric_space': metric_space,
                'model': model_name,
            }

            for split_name, split_df in [
                ('train', trainer.train_df),
                ('validation', trainer.val_df),
            ]:
                scores = score_model_split(
                    model=model,
                    split_df=split_df,
                    feature_cols=feature_cols,
                    target_col=spec['target_col'],
                    native_space=spec['native_space'],
                    metric_space=metric_space,
                )
                for metric_name, metric_value in scores.items():
                    row[f'{split_name}_{metric_name}'] = metric_value

            records.append(row)

all_results = pd.DataFrame(records)
DISPLAY_COLS = [
    'dataset', 'embedding_model', 'variant', 'embedding_cols',
    'native_space', 'metric_space', 'model',
    'train_mae', 'validation_mae',
    'train_rmse', 'validation_rmse',
    'train_r2', 'validation_r2',
]

all_results[DISPLAY_COLS].sort_values(['metric_space', 'validation_rmse', 'validation_mae']).reset_index(drop=True)

## Log-Space Leaderboard

In [7]:
log_results = all_results.query("metric_space == 'log'").copy()
log_results[DISPLAY_COLS].sort_values(['validation_rmse', 'validation_mae']).reset_index(drop=True)

,dataset,embedding_model,variant,embedding_cols,native_space,metric_space,model,train_mae,validation_mae,test_mae,train_rmse,validation_rmse,test_rmse,train_r2,validation_r2,test_r2
0,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,log,random_forest,0.006494,0.030423,0.025817,0.031862,0.129201,0.102832,0.967452,0.700868,0.738357
1,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,log,xgboost,0.011188,0.029773,0.024470,0.050109,0.130405,0.101163,0.919493,0.695269,0.746784
2,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,log,random_forest,0.007537,0.031478,0.029549,0.035766,0.130863,0.114768,0.958986,0.693121,0.674092
3,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,log,random_forest,0.006772,0.032153,0.030127,0.032031,0.131996,0.114281,0.967105,0.687785,0.676853
4,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,log,random_forest,0.007942,0.035185,0.035266,0.037012,0.136176,0.125540,0.956079,0.667699,0.610045
5,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,log,xgboost,0.013355,0.030482,0.026345,0.062539,0.136432,0.112552,0.874600,0.666447,0.686555
6,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,log,xgboost,0.015296,0.034692,0.031551,0.061114,0.138507,0.124926,0.880248,0.656226,0.613851
7,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,log,xgboost,0.016089,0.037414,0.035908,0.066326,0.147236,0.133681,0.858955,0.611531,0.557828
8,node2vec_original,Node2Vec,original,64,log,log,random_forest,0.008466,0.038476,0.030545,0.040040,0.184099,0.147009,0.948598,0.392657,0.465261
9,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,log,linear_regression,0.058798,0.080441,0.074960,0.144037,0.197041,0.167245,0.334815,0.304266,0.307922
10,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,log,ridge,0.058785,0.080419,0.074938,0.144037,0.197046,0.167243,0.334815,0.304231,0.307932
11,node2vec_original,Node2Vec,original,64,log,log,xgboost,0.013738,0.037834,0.029069,0.060910,0.201278,0.161593,0.881047,0.274027,0.353909
12,graphsage_original,GraphSAGE,original,64,log,log,random_forest,0.006973,0.034803,0.028440,0.038312,0.206160,0.172369,0.952940,0.238379,0.264864
13,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,log,ridge,0.055000,0.077092,0.080197,0.135624,0.212803,0.230185,0.410249,0.188509,-0.311003
14,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,log,linear_regression,0.055009,0.077104,0.080212,0.135624,0.212804,0.230203,0.410249,0.188497,-0.311218
15,graphsage_original,GraphSAGE,original,64,log,log,xgboost,0.011587,0.036349,0.030472,0.061764,0.227886,0.198775,0.877690,0.069398,0.022373
16,graphsage_original,GraphSAGE,original,64,log,log,ridge,0.050552,0.070938,0.080051,0.152026,0.238091,0.235203,0.258978,-0.015818,-0.368793
17,graphsage_original,GraphSAGE,original,64,log,log,linear_regression,0.050552,0.070938,0.080053,0.152026,0.238091,0.235204,0.258978,-0.015819,-0.368808
18,node2vec_original,Node2Vec,original,64,log,log,ridge,0.059122,0.068984,0.065145,0.163570,0.252306,0.199272,0.142172,-0.140733,0.017473
19,node2vec_original,Node2Vec,original,64,log,log,linear_regression,0.059122,0.068984,0.065145,0.163570,0.252306,0.199272,0.142172,-0.140735,0.017473
20,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,log,ridge,0.138884,0.163651,0.148122,0.223174,0.258352,0.226717,-0.596919,-0.196065,-0.271802
21,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,log,linear_regression,0.138892,0.163687,0.148168,0.223186,0.258388,0.226763,-0.597086,-0.196390,-0.272318
22,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,log,ridge,0.183185,0.186817,0.179943,0.264662,0.279113,0.258379,-1.245843,-0.396014,-0.651837
23,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,log,linear_regression,0.183208,0.186825,0.179947,0.264685,0.279122,0.258383,-1.246228,-0.396099,-0.651879
24,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,log,random_forest,0.006006,0.129821,0.121977,0.033576,0.354567,0.298949,0.963855,-1.252823,-1.211295
25,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,log,xgboost,0.011602,0.162925,0.135490,0.053980,0.397317,0.324009,0.906576,-1.828809,-1.597551
26,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,log,linear_regression,0.050143,0.181920,0.113078,0.154467,0.500860,0.258030,0.234990,-3.495334,-0.647374
27,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,log,xgboost,0.017944,0.325346,0.479794,0.068363,0.786384,0.968642,0.850157,-10.081499,-22.215495
28,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,log,ridge,0.050196,0.309518,0.077771,0.153664,0.839892,0.203605,0.242926,-11.640850,-0.025718
29,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,log,linear_regression,0.155504,0.446183,0.558040,0.256000,0.855312,1.021719,-1.101243,-12.109288,-24.829404
30,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,log,random_forest,0.007295,0.404350,0.597851,0.044532,0.948938,1.185398,0.936417,-15.136334,-33.767972
31,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,log,ridge,0.145828,0.462368,0.550494,0.255648,0.982541,1.085201,-1.095454,-16.299398,-28.138781
32,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,log,linear_regression,0.145937,0.462609,0.550858,0.255800,0.982973,1.085804,-1.097951,-16.314609,-28.171206
33,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,log,ridge,0.155387,0.502343,0.511864,0.253562,0.986592,0.944334,-1.061404,-16.442356,-21.064935
34,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,log,xgboost,0.018206,0.472193,0.381711,0.065319,0.993194,0.773496,0.863205,-16.676557,-13.803608
35,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,log,random_forest,0.008380,0.532557,0.456681,0.049566,1.120270,0.913700,0.921230,-21.489234,-19.656578

## Original-Scale (`out`) Leaderboard

In [8]:
out_results = all_results.query("metric_space == 'out'").copy()
out_results[DISPLAY_COLS].sort_values(['validation_rmse', 'validation_mae']).reset_index(drop=True)

,dataset,embedding_model,variant,embedding_cols,native_space,metric_space,model,train_mae,validation_mae,test_mae,train_rmse,validation_rmse,test_rmse,train_r2,validation_r2,test_r2
0,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,out,random_forest,0.031658,0.156183,0.147287,0.341280,1.114571,1.129883,0.966533,0.866449,0.674042
1,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,out,random_forest,0.029302,0.149306,0.119254,0.322992,1.160822,0.848385,0.970024,0.855135,0.816227
2,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,out,random_forest,0.030585,0.153138,0.132928,0.479702,1.244759,1.385212,0.933880,0.833428,0.510078
3,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,out,xgboost,0.036302,0.154222,0.107992,0.239300,1.401684,0.975655,0.983546,0.788782,0.756955
4,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,out,xgboost,0.043733,0.170745,0.125627,0.219575,1.471841,0.873980,0.986147,0.767109,0.804972
5,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,out,random_forest,0.030307,0.172021,0.135181,0.424323,1.580922,1.190057,0.948265,0.731310,0.638399
6,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,out,xgboost,0.043950,0.179892,0.124987,0.318644,1.921386,1.145960,0.970825,0.603119,0.664700
7,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,out,xgboost,0.047181,0.202500,0.150238,0.253275,1.974640,1.096034,0.981568,0.580814,0.693280
8,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,out,linear_regression,0.383542,0.540306,0.450386,1.471555,2.437767,1.461340,0.377780,0.361125,0.454749
9,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,out,ridge,0.383487,0.540223,0.450285,1.471555,2.437915,1.461422,0.377780,0.361048,0.454688
10,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,out,linear_regression,0.486138,0.581225,0.520926,1.559753,2.544153,1.598091,0.300959,0.304147,0.347925
11,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,out,ridge,0.486074,0.581203,0.520911,1.559753,2.544247,1.598140,0.300959,0.304095,0.347885
12,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,out,linear_regression,0.178981,0.397180,0.357719,1.709268,2.611217,1.886740,0.160518,0.266978,0.091094
13,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,out,linear_regression,0.179523,0.307515,0.233554,1.556394,2.614361,1.460623,0.303966,0.265212,0.455283
14,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,out,ridge,0.179512,0.307499,0.233535,1.556507,2.614520,1.460784,0.303865,0.265122,0.455163
15,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,out,ridge,0.178517,0.474367,0.250575,1.699544,2.691662,2.119090,0.170043,0.221117,-0.146551
16,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,out,xgboost,0.044529,0.693873,0.483286,0.430612,2.728761,1.706377,0.946720,0.199498,0.256562
17,node2vec_original,Node2Vec,original,64,log,out,random_forest,0.046092,0.243959,0.162372,0.694915,2.771738,1.713036,0.861243,0.174085,0.250749
18,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,out,linear_regression,0.193443,0.327866,0.249028,1.693111,2.829075,1.748613,0.176313,0.139561,0.219304
19,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,out,ridge,0.193425,0.327831,0.248986,1.693229,2.829241,1.748746,0.176199,0.139460,0.219185
20,node2vec_original,Node2Vec,original,64,log,out,xgboost,0.045543,0.248449,0.163276,0.297238,2.912768,1.813384,0.974614,0.087899,0.160397
21,graphsage_original,GraphSAGE,original,64,log,out,random_forest,0.042693,0.242967,0.165586,0.768498,2.977878,1.904165,0.830302,0.046666,0.074229
22,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,out,random_forest,0.037098,0.617713,0.438763,0.605602,3.019356,1.692034,0.894618,0.019924,0.269008
23,graphsage_original,GraphSAGE,original,64,log,out,xgboost,0.058694,0.246615,0.170146,0.855556,3.034061,1.975559,0.789676,0.010354,0.003506
24,graphsage_original,GraphSAGE,original,64,log,out,linear_regression,0.180713,0.314793,0.267303,1.715806,3.040820,2.033763,0.154084,0.005940,-0.056075
25,graphsage_original,GraphSAGE,original,64,log,out,ridge,0.180713,0.314792,0.267301,1.715808,3.040821,2.033759,0.154082,0.005940,-0.056071
26,node2vec_original,Node2Vec,original,64,log,out,ridge,0.200756,0.311551,0.238446,1.808109,3.079134,1.952711,0.060622,-0.019268,0.026423
27,node2vec_original,Node2Vec,original,64,log,out,linear_regression,0.200757,0.311552,0.238446,1.808108,3.079134,1.952711,0.060623,-0.019268,0.026423
28,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,out,xgboost,0.053611,2.307629,3.373531,0.277813,6.739086,8.210081,0.977823,-3.882397,-16.210335
29,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,out,linear_regression,0.405333,2.762905,4.105708,1.532965,7.469816,10.926438,0.324764,-4.998614,-29.482574
30,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,out,xgboost,0.052579,3.635512,2.067499,0.259297,8.768371,4.963400,0.980681,-7.265497,-5.290033
31,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,out,ridge,0.403975,3.882682,3.331630,1.505285,10.495238,8.485031,0.348928,-10.841744,-17.382361
32,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,out,random_forest,0.034693,3.686210,5.548695,0.445772,10.748938,13.082956,0.942903,-11.421160,-42.702489
33,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,out,random_forest,0.036565,4.885584,2.914301,0.429405,11.662460,6.808645,0.947018,-13.622156,-10.836295
34,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,out,ridge,0.392066,4.091182,5.115594,1.663739,12.345768,15.118423,0.204644,-15.385787,-57.358943
35,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,out,linear_regression,0.392350,4.095633,5.123203,1.663739,12.358453,15.141143,0.204644,-15.419476,-57.534477

## Best Model Per Embedding Dataset

In [9]:
best_by_dataset = (
    all_results
    .sort_values(['metric_space', 'dataset', 'validation_rmse', 'validation_mae'])
    .groupby(['metric_space', 'dataset'], as_index=False)
    .first()
)

best_by_dataset[DISPLAY_COLS].sort_values(['metric_space', 'validation_rmse', 'validation_mae']).reset_index(drop=True)

,dataset,embedding_model,variant,embedding_cols,native_space,metric_space,model,train_mae,validation_mae,test_mae,train_rmse,validation_rmse,test_rmse,train_r2,validation_r2,test_r2
0,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,log,random_forest,0.006494,0.030423,0.025817,0.031862,0.129201,0.102832,0.967452,0.700868,0.738357
1,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,log,random_forest,0.007537,0.031478,0.029549,0.035766,0.130863,0.114768,0.958986,0.693121,0.674092
2,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,log,random_forest,0.006772,0.032153,0.030127,0.032031,0.131996,0.114281,0.967105,0.687785,0.676853
3,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,log,random_forest,0.007942,0.035185,0.035266,0.037012,0.136176,0.125540,0.956079,0.667699,0.610045
4,node2vec_original,Node2Vec,original,64,log,log,random_forest,0.008466,0.038476,0.030545,0.040040,0.184099,0.147009,0.948598,0.392657,0.465261
5,graphsage_original,GraphSAGE,original,64,log,log,random_forest,0.006973,0.034803,0.028440,0.038312,0.206160,0.172369,0.952940,0.238379,0.264864
6,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,log,random_forest,0.006006,0.129821,0.121977,0.033576,0.354567,0.298949,0.963855,-1.252823,-1.211295
7,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,log,xgboost,0.017944,0.325346,0.479794,0.068363,0.786384,0.968642,0.850157,-10.081499,-22.215495
8,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,log,linear_regression,0.155504,0.446183,0.558040,0.256000,0.855312,1.021719,-1.101243,-12.109288,-24.829404
9,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,out,random_forest,0.031658,0.156183,0.147287,0.341280,1.114571,1.129883,0.966533,0.866449,0.674042
10,node2vec_fixed_64_out,Node2Vec,fixed_64,64,out,out,random_forest,0.029302,0.149306,0.119254,0.322992,1.160822,0.848385,0.970024,0.855135,0.816227
11,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,out,random_forest,0.030585,0.153138,0.132928,0.479702,1.244759,1.385212,0.933880,0.833428,0.510078
12,node2vec_fixed_32_log,Node2Vec,fixed_32,32,log,out,random_forest,0.030307,0.172021,0.135181,0.424323,1.580922,1.190057,0.948265,0.731310,0.638399
13,graphsage_fixed_32_log,GraphSAGE,fixed_32,32,log,out,linear_regression,0.178981,0.397180,0.357719,1.709268,2.611217,1.886740,0.160518,0.266978,0.091094
14,node2vec_original,Node2Vec,original,64,log,out,random_forest,0.046092,0.243959,0.162372,0.694915,2.771738,1.713036,0.861243,0.174085,0.250749
15,graphsage_original,GraphSAGE,original,64,log,out,random_forest,0.042693,0.242967,0.165586,0.768498,2.977878,1.904165,0.830302,0.046666,0.074229
16,graphsage_fixed_32_out,GraphSAGE,fixed_32,32,out,out,xgboost,0.053611,2.307629,3.373531,0.277813,6.739086,8.210081,0.977823,-3.882397,-16.210335
17,graphsage_fixed_64_out,GraphSAGE,fixed_64,64,out,out,linear_regression,0.405333,2.762905,4.105708,1.532965,7.469816,10.926438,0.324764,-4.998614,-29.482574

## Compact Pivot View

This table keeps the best model for each dataset and shows validation RMSE and MAE side by side under `log` and `out` metric spaces.

In [ ]:
pivot = (
    best_by_dataset
    .pivot_table(
        index=['dataset', 'embedding_model', 'variant', 'embedding_cols', 'native_space'],
        columns='metric_space',
        values=['validation_rmse', 'validation_mae'],
        aggfunc='first',
    )
)

pivot.columns = [f'{metric}_{space}' for metric, space in pivot.columns]
pivot = pivot.reset_index()

pivot.sort_values(['validation_rmse_log', 'validation_mae_log']).reset_index(drop=True)

## Overall Winners

In [11]:
overall_winners = (
    all_results
    .sort_values(['metric_space', 'validation_rmse', 'validation_mae'])
    .groupby('metric_space', as_index=False)
    .first()
)

overall_winners[DISPLAY_COLS]

,dataset,embedding_model,variant,embedding_cols,native_space,metric_space,model,train_mae,validation_mae,test_mae,train_rmse,validation_rmse,test_rmse,train_r2,validation_r2,test_r2
0,node2vec_fixed_128_log,Node2Vec,fixed_128,128,log,log,random_forest,0.006494,0.030423,0.025817,0.031862,0.129201,0.102832,0.967452,0.700868,0.738357
1,node2vec_fixed_32_out,Node2Vec,fixed_32,32,out,out,random_forest,0.031658,0.156183,0.147287,0.341280,1.114571,1.129883,0.966533,0.866449,0.674042